In [1]:
import pandas as pd

In [24]:
# Read in voter_reg.csv which is tab deliminated
voter_hist_df = pd.read_csv("Resources/voter_hist.csv", sep='\t',  lineterminator='\n')

In [54]:
voter_hist_df.head()

,county_id,county_desc,voter_reg_num,election_lbl,election_desc,voting_method,voted_party_cd,voted_party_desc,pct_label,pct_description,ncid,voted_county_id,voted_county_desc,vtd_label,vtd_description\r
0,11,BUNCOMBE,351521,11/03/2020,11/03/2020 GENERAL,ABSENTEE ONESTOP,REP,REPUBLICAN,29.2,29.2,AA103340,11,BUNCOMBE,102.1,102.1\r
1,11,BUNCOMBE,351521,11/04/2014,11/04/2014 GENERAL,ABSENTEE ONESTOP,REP,REPUBLICAN,39.3,39.3,AA103340,11,BUNCOMBE,39.1,39.1\r
2,11,BUNCOMBE,351521,11/06/2012,11/06/2012 GENERAL,ABSENTEE ONESTOP,REP,REPUBLICAN,39.3,39.3,AA103340,11,BUNCOMBE,39.1,39.1\r
3,11,BUNCOMBE,309287,11/06/2012,11/06/2012 GENERAL,ABSENTEE ONESTOP,UNA,UNAFFILIATED,11.1,11.1,AA104672,11,BUNCOMBE,11.1,11.1\r
4,11,BUNCOMBE,309287,05/08/2012,05/08/2012 PRIMARY,IN-PERSON,DEM,DEMOCRATIC,11.1,11.1,AA104672,11,BUNCOMBE,11.1,11.1\r

In [30]:
# Get list of all column names
hist_columns = list(voter_hist_df.columns)
hist_columns

['county_id',
 'county_desc',
 'voter_reg_num',
 'election_lbl',
 'election_desc',
 'voting_method',
 'voted_party_cd',
 'voted_party_desc',
 'pct_label',
 'pct_description',
 'ncid',
 'voted_county_id',
 'voted_county_desc',
 'vtd_label',
 'vtd_description\r']

In [27]:
# Read in voter_reg.csv which is tab deliminated and encoded with cp1252
voter_reg_df = pd.read_csv("Resources/voter_reg.csv", sep='\t',  lineterminator='\n', encoding='cp1252')

In [28]:
voter_reg_df.head()

,county_id,county_desc,voter_reg_num,status_cd,voter_status_desc,reason_cd,voter_status_reason_desc,absent_ind,name_prefx_cd,last_name,...,munic_dist_desc,dist_1_abbrv,dist_1_desc,dist_2_abbrv,dist_2_desc,confidential_ind,birth_year,ncid,vtd_abbrv,vtd_desc\r
0,11,BUNCOMBE,378389,A,ACTIVE,AV,VERIFIED,,,A-AKERT,...,NaN,40.0,40TH PROSECUTORIAL,,,N,1956,AL270949,52.1,52.1\r
1,11,BUNCOMBE,381829,A,ACTIVE,AV,VERIFIED,,,A-AKERT,...,NaN,40.0,40TH PROSECUTORIAL,,,N,1952,AL273503,52.1,52.1\r
2,11,BUNCOMBE,425478,A,ACTIVE,AV,VERIFIED,,,AAB,...,NaN,40.0,40TH PROSECUTORIAL,,,N,1974,CW939539,68.1,68.1\r
3,11,BUNCOMBE,425477,A,ACTIVE,AV,VERIFIED,,,AAB,...,NaN,40.0,40TH PROSECUTORIAL,,,N,1981,CW988432,68.1,68.1\r
4,11,BUNCOMBE,429468,A,ACTIVE,AV,VERIFIED,,,AABYE,...,NaN,40.0,40TH PROSECUTORIAL,,,N,1981,DM19859,60.2,60.2\r

In [31]:
reg_columns = list(voter_reg_df.columns)
reg_columns

['county_id',
 'county_desc',
 'voter_reg_num',
 'status_cd',
 'voter_status_desc',
 'reason_cd',
 'voter_status_reason_desc',
 'absent_ind',
 'name_prefx_cd',
 'last_name',
 'first_name',
 'middle_name',
 'name_suffix_lbl',
 'res_street_address',
 'res_city_desc',
 'state_cd',
 'zip_code',
 'mail_addr1',
 'mail_addr2',
 'mail_addr3',
 'mail_addr4',
 'mail_city',
 'mail_state',
 'mail_zipcode',
 'full_phone_number',
 'race_code',
 'ethnic_code',
 'party_cd',
 'gender_code',
 'birth_age',
 'birth_state',
 'drivers_lic',
 'registr_dt',
 'precinct_abbrv',
 'precinct_desc',
 'municipality_abbrv',
 'municipality_desc',
 'ward_abbrv',
 'ward_desc',
 'cong_dist_abbrv',
 'super_court_abbrv',
 'judic_dist_abbrv',
 'nc_senate_abbrv',
 'nc_house_abbrv',
 'county_commiss_abbrv',
 'county_commiss_desc',
 'township_abbrv',
 'township_desc',
 'school_dist_abbrv',
 'school_dist_desc',
 'fire_dist_abbrv',
 'fire_dist_desc',
 'water_dist_abbrv',
 'water_dist_desc',
 'sewer_dist_abbrv',
 'sewer_dist_desc',
 'sanit_dist_abbrv',
 'sanit_dist_desc',
 'rescue_dist_abbrv',
 'rescue_dist_desc',
 'munic_dist_abbrv',
 'munic_dist_desc',
 'dist_1_abbrv',
 'dist_1_desc',
 'dist_2_abbrv',
 'dist_2_desc',
 'confidential_ind',
 'birth_year',
 'ncid',
 'vtd_abbrv',
 'vtd_desc\r']

In [49]:
# Drop unnecessary columns
voter_reg_df.drop(['dist_2_desc', 'dist_1_desc', 'munic_dist_desc', 'rescue_dist_desc', 'sanit_dist_desc', 'sewer_dist_desc',
                  'water_dist_desc', 'fire_dist_desc', 'school_dist_desc', 'township_desc', 'county_commiss_desc', 
                  'ward_desc', 'municipality_desc', 'absent_ind', 'name_prefx_cd', 'dist_2_abbrv'], axis=1, inplace=True)
voter_reg_df

,county_id,county_desc,voter_reg_num,status_cd,voter_status_desc,reason_cd,voter_status_reason_desc,last_name,first_name,middle_name,...,sewer_dist_abbrv,sanit_dist_abbrv,rescue_dist_abbrv,munic_dist_abbrv,dist_1_abbrv,confidential_ind,birth_year,ncid,vtd_abbrv,vtd_desc\r
0,11,BUNCOMBE,378389,A,ACTIVE,AV,VERIFIED,A-AKERT,DIANE,FAE,...,NaN,NaN,NaN,NaN,40.0,N,1956,AL270949,52.1,52.1\r
1,11,BUNCOMBE,381829,A,ACTIVE,AV,VERIFIED,A-AKERT,WALTER,DEAN,...,NaN,NaN,NaN,NaN,40.0,N,1952,AL273503,52.1,52.1\r
2,11,BUNCOMBE,425478,A,ACTIVE,AV,VERIFIED,AAB,KERRI,NaN,...,NaN,NaN,NaN,NaN,40.0,N,1974,CW939539,68.1,68.1\r
3,11,BUNCOMBE,425477,A,ACTIVE,AV,VERIFIED,AAB,RICHARD,EDWARD,...,NaN,NaN,NaN,NaN,40.0,N,1981,CW988432,68.1,68.1\r
4,11,BUNCOMBE,429468,A,ACTIVE,AV,VERIFIED,AABYE,MEREDITH,MICHELLE,...,NaN,NaN,NaN,NaN,40.0,N,1981,DM19859,60.2,60.2\r
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237011,11,BUNCOMBE,316274,A,ACTIVE,AV,VERIFIED,ZYLA,JENNIFER,ANNE,...,NaN,NaN,NaN,NaN,40.0,N,1977,AL222272,47.1,47.1\r
237012,11,BUNCOMBE,509668,A,ACTIVE,AV,VERIFIED,ZYNA,JASON,MATTHEW,...,NaN,NaN,NaN,ASH,40.0,N,1976,AL362059,15.1,15.1\r
237013,11,BUNCOMBE,462204,A,ACTIVE,AV,VERIFIED,ZYNDA,MALLORY,JO,...,NaN,NaN,NaN,ASH,40.0,N,1997,AL303682,102.1,102.1\r
237014,11,BUNCOMBE,430663,A,ACTIVE,AV,VERIFIED,ZYNDA,PATRICK,ARTHUR JOSEPH,...,NaN,NaN,NaN,ASH,40.0,N,1996,AL308726,102.1,102.1\r
237015,11,BUNCOMBE,411679,A,ACTIVE,AV,VERIFIED,ZYRY,RUTH,ANN,...,NaN,NaN,NaN,NaN,40.0,N,1971,AL295547,39.1,39.1\r

In [51]:
reg_columns = list(voter_reg_df.columns)
reg_columns

['county_id',
 'county_desc',
 'voter_reg_num',
 'status_cd',
 'voter_status_desc',
 'reason_cd',
 'voter_status_reason_desc',
 'last_name',
 'first_name',
 'middle_name',
 'name_suffix_lbl',
 'res_street_address',
 'res_city_desc',
 'state_cd',
 'zip_code',
 'mail_addr1',
 'mail_addr2',
 'mail_addr3',
 'mail_addr4',
 'mail_city',
 'mail_state',
 'mail_zipcode',
 'full_phone_number',
 'race_code',
 'ethnic_code',
 'party_cd',
 'gender_code',
 'birth_age',
 'birth_state',
 'drivers_lic',
 'registr_dt',
 'precinct_abbrv',
 'precinct_desc',
 'municipality_abbrv',
 'ward_abbrv',
 'cong_dist_abbrv',
 'super_court_abbrv',
 'judic_dist_abbrv',
 'nc_senate_abbrv',
 'nc_house_abbrv',
 'county_commiss_abbrv',
 'township_abbrv',
 'school_dist_abbrv',
 'fire_dist_abbrv',
 'water_dist_abbrv',
 'sewer_dist_abbrv',
 'sanit_dist_abbrv',
 'rescue_dist_abbrv',
 'munic_dist_abbrv',
 'dist_1_abbrv',
 'confidential_ind',
 'birth_year',
 'ncid',
 'vtd_abbrv',
 'vtd_desc\r']

In [36]:
# Determine number of row in csv
in_csv = 'Resources/voter_hist.csv'

number_lines = sum(1 for row in (open(in_csv)))
number_lines

1072106

In [45]:
# Split csv into 2 equal sized csv's so that they can be pushed to github
from __future__ import division

numrows = 536053 #number of rows per csv
count = 0 #keep track of chunks
chunkrows = 100000 #read 100k rows at a time
df = pd.read_csv('Resources/voter_hist.csv', sep='\t',  lineterminator='\n', iterator=True, chunksize=chunkrows) 
for chunk in df: #for each 100k rows
    if count <= numrows/chunkrows: #if threshold has not been reached 
        outname = "voter_hist1.csv"
    else:
        outname = "voter_hist2.csv"
    #append each output to same csv, using no header
    chunk.to_csv(outname, header=True, mode='a', index=None)
    count+=1

In [46]:
# Determine number of row in csv
in_csv = 'Resources/voter_reg.csv'

number_lines = sum(1 for row in (open(in_csv)))
number_lines

237017

In [47]:
# Split csv into 2 equal sized csv's so that they can be pushed to github
from __future__ import division

numrows = 118509 #number of rows per csv
count = 0 #keep track of chunks
chunkrows = 100000 #read 100k rows at a time
df = pd.read_csv('Resources/voter_reg.csv', sep='\t',  lineterminator='\n', iterator=True, encoding='cp1252', chunksize=chunkrows) 
for chunk in df: #for each 100k rows
    if count <= numrows/chunkrows: #if threshold has not been reached 
        outname = "voter_reg1.csv"
    else:
        outname = "voter_reg2.csv"
    #append each output to same csv, using no header
    chunk.to_csv(outname, header=True, mode='a', index=None)
    count+=1